services:
  webapp:
    environment:
      - NODE_ENV=test
      - WATCHPACK_POLLING=true
    volumes:
      - ./apps/webapp/tests-playwright:/app/apps/webapp/tests-playwright
    command: >
      sh -c "npx playwright install --with-deps && 
             npm run test:playwright"

  # don't run the inference server for tests for now
  # later on we do want this
  inference:
    command: "tail -f /dev/null"
