services:
  inference:
    volumes:
      - ./apps/inference:/app/apps/inference
    environment:
      - RELOAD=${RELOAD:-0}
    command: >
      sh -c "if [ "$$RELOAD" = "1" ]; then
        python start.py --reload;
      else
        python start.py;
      fi"
